rollback clear script

diff --git a/clear_runs_without_checkpoints b/clear_runs_without_checkpoints
--- a/clear_runs_without_checkpoints
+++ b/clear_runs_without_checkpoints
@@ -1,44 +1,32 @@
 #!/bin/bash
 
-declare -a TASKS=("colon" "endo" "chest")
-declare -a SHOTS=("1" "5" "10")
-
-# If arguments are provided, only process for the specific task and shot
-if [ "$#" -eq 2 ]; then
-    TASKS=("$1")
-    SHOTS=("$2")
-elif [ "$#" -gt 2 ]; then
-    echo "Usage: $0 [task] [shot]"
+# Check the number of arguments provided
+if [ "$#" -ne 2 ]; then
+    echo "Usage: $0 <task> <shot>"
     echo "E.g.: ./clear_runs_without_checkpoints colon 1"
-    echo "Without arguments, all combinations will be processed."
     exit 1
 fi
 
-for TASK in "${TASKS[@]}"; do
-    for SHOT in "${SHOTS[@]}"; do
-        DIRECTORY="work_dirs/${TASK}/${SHOT}-shot/"
+TASK="$1"
+SHOT="$2"
+DIRECTORY="work_dirs/${TASK}/${SHOT}-shot/"
 
-        # Check if the target directory exists
-        if [ ! -d "$DIRECTORY" ]; then
-            echo "Error: Directory ${DIRECTORY} does not exist."
-            continue
-        fi
+# Check if the target directory exists
+if [ ! -d "$DIRECTORY" ]; then
+    echo "Error: Directory ${DIRECTORY} does not exist."
+    exit 1
+fi
 
-        echo "Deleting all dirs without .pth files in ${DIRECTORY}"
+echo "Deleting all dirs without .pth files in ${DIRECTORY}"
 
-        # Switch to the target directory
-        cd "${DIRECTORY}" || exit
+# Switch to the target directory
+cd "${DIRECTORY}"
 
-        for dir in */; do
-            # Check if the directory contains any .pth files
-            if [ "$(find "${dir}" -maxdepth 1 -type f -name "*.pth" | wc -l)" -eq 0 ]; then
-                echo "Deleting dir: ${dir}"
-                rm -r "${dir}"
-            fi
-        done
-
-        # Switch back to the original directory so that the outer loops can continue correctly
-        cd - > /dev/null || exit
-
-    done
+for dir in */; do
+    # Check if the directory contains any .pth files
+    if [ $(find "${dir}" -maxdepth 1 -type f -name "*.pth" | wc -l) -eq 0 ]; then
+        echo "Deleting dir: ${dir}"
+        rm -r "${dir}"
+    fi
 done
+
